on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      project:
        required: true
        type: string

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.environment == 'prod' && secrets.PROD_ROLE_TO_ASSUME || secrets.DEV_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ vars.AWS_DEV_ACCOUNT }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.CICD_GITHUB_REPO }}
          token: ${{ secrets.CICD_REPO_READ_TOKEN }}
          path: cicd

      - name: Deploy
        uses: ./cicd/actions/eks-action
        env:
          cluster_name: ${{ inputs.eks_cluster_name }}
          IMAGE_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          PROJECT: ${{ inputs.project }}
        with:
          args: bash cicd/charts/deploy-$PROJECT.sh ${{ inputs.environment }}