on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      project:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      aws_ecr_account:
        required: true
        type: string
      github_cicd_repo:
        required: true
        type: string
      eks_cluster:
        required: true
        type: string

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.environment == 'prod' && secrets.PROD_ROLE_TO_ASSUME || secrets.DEV_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ inputs.aws_ecr_account }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.github_cicd_repo }}
          token: ${{ secrets.CICD_REPO_READ_TOKEN }}
          path: cicd

      - name: Deploy
        uses: ./cicd/actions/eks-action
        env:
          cluster_name: ${{ inputs.eks_cluster }}
          IMAGE_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          PROJECT: ${{ inputs.project }}
        with:
          args: bash cicd/charts/deploy-${{ inputs.project }}.sh ${{ inputs.environment }}